[package]
name = "sqlite3-sys"
version = "0.6.7"
authors = ["Ivan Ukhov <ivan.ukhov@gmail.com>"]
license = "MIT"
repository = "https://github.com/stainless-steel/sqlite3-sys"
homepage = "https://github.com/stainless-steel/sqlite3-sys"
documentation = "https://stainless-steel.github.io/sqlite3-sys"
description = "The package provides bindings to SQLite."
build = "build.rs"
links = "sqlite3"

[dependencies]
libc = "0.2"

[build-dependencies]
pkg-config = "0.3"

[dev-dependencies]
temporary = "0.5"
