[package]
name = "sqlite3-sys"
version = "0.6.7"
license = "Apache-2.0/MIT"
authors = ["Ivan Ukhov <ivan.ukhov@gmail.com>"]
description = "The package provides bindings to SQLite."
documentation = "https://stainless-steel.github.io/sqlite3-sys"
homepage = "https://github.com/stainless-steel/sqlite3-sys"
repository = "https://github.com/stainless-steel/sqlite3-sys"
build = "build.rs"
links = "sqlite3"

[dependencies]
libc = "0.2"

[build-dependencies]
pkg-config = "0.3"

[dev-dependencies]
temporary = "0.5"

[features]
# Link against sqlcipher, instead of sqlite3, enabling support for
# transparent database encryption.
sqlcipher = []
