[package]
name = "sqlite3-sys"
version = "0.8.0"
license = "Apache-2.0/MIT"
authors = [
  "Ivan Stankovic <pokemon@fly.srk.fer.hr>",
  "Ivan Ukhov <ivan.ukhov@gmail.com>",
]
description = "The package provides bindings to SQLite."
documentation = "https://stainless-steel.github.io/sqlite3-sys"
homepage = "https://github.com/stainless-steel/sqlite3-sys"
repository = "https://github.com/stainless-steel/sqlite3-sys"

[features]
default = ["standard"]

standard = ["sqlite3-provider"]
sqlcipher = ["sqlcipher-provider"]

[dependencies]
libc = "0.2"

[dependencies.sqlite3-provider]
version = "0.0.1"
optional = true

[dependencies.sqlcipher-provider]
version = "0.0.1"
optional = true

[dev-dependencies]
temporary = "0.5"
